### ISSUE TITLE
Configure Travis task to execute tests for all examples

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xc#42]
This will ensure that none of our example code fails to pass tests

**Comment by palisaide** [comment]
So, I wrote a simple script that we could potentially use for this.  Right now it is written with the assumption that all exercises will have only `example.c` and `example.h` under the `src` directory.  It figures out what these files should be named based on the `test_*.c` file, then it renames them accordingly and executes `make`.  However, this won't work if we are going to be providing a partial solution (like #43 suggests).

**Comment by palisaide** [comment]
Actually, I'm wrong.  It can work.  It just needs to check to see if the `example` c/h file exists.  If not, assume that the exercise-named file is present.

**Comment by kytrinyx** [comment]
The one thing I would be careful of (speaking from painful experience), is that if we rename files, we risk accidentally checking in the renamed ones. The solution we've had to this previously is to copy the entire source directory to a temporary directory somewhere, and then rename them in the tmpdir rather than in the original location, and run the tests there.

**Comment by ryanplusplus** [comment]
Hey @kytrinyx, I think this is intended to be run by Travis. However, I think we can make it safe for other situations by first copying all files into a folder which is listed in `.gitignore` to ensure that none of the created files are visible to git.

**Comment by kytrinyx** [comment]
That sounds like a good plan, @ryanplusplus
