### ISSUE TITLE
Should we provide the solution's header and empty source file?

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xc#43]
Including a (more or less) completed header will help set to ensure that solutions are const-correct and help to communicate all assumptions made about arguments in the tests.

Including an empty source file will help to ensure that the user can get _something_ compiling relatively quickly.

**Comment by patricksjackson** [comment]
Including stubs seems to be a point of debate for every track at some point :)

I think forcing the solver to define the function definition themselves is good, it makes them have to consider what exactly they need to do. Doing it yourself rather than having it handed to you is a better way to learn.

The first problem or two should probably have them though.

**Comment by ryanplusplus** [comment]
@patricksjackson that makes sense to me. I'll create a PR to add a stub for the hello world problem.
