### ISSUE TITLE
Hello World -- limited buffer size seems like too much for an introduction exercise

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xc#56]
The hello world exercise tests that the implementation is careful not to write out of bounds. While this is good practice, it seems excessive for a hello world. This may be someone's first exposure to C, to unit testing, and to Exercism, so it seems that we should save buffer overflows for a later topic.

I'd like to update the hello world exercise to use a comically over-sized buffer and save this topic for a later exercise. Thoughts?

**Comment by patricksjackson** [comment]
I think it's a bit over the top to have a Hello World exercise where you have to print into a buffer (after, of course, you figure out that's what you're supposed to do), understand how strings terminate, understand NULL pointers (potentially), and understand what buffer overflow even _is_.

I'm in favor of making Hello World as easy as possible, but even throwing out the need to check the buffer size still doesn't make it easy to understand. I don't see how it can be an easy C intro while still enabling unit tests.

(I think a lot of the problems are very string heavy for C, so that's just going to be a problem.)

**Comment by kytrinyx** [comment]
> I'm in favor of making Hello World as easy as possible

💯 percent!

**Comment by kytrinyx** [comment]
> I think a lot of the problems are very string heavy for C, so that's just going to be a problem.

We might be able to skip some of the string-heavy stuff in this track, and also we can put string-heavy stuff towards the end of the list, if it's harder to deal with.

**Comment by ryanplusplus** [comment]
> We might be able to skip some of the string-heavy stuff in this track, and also we can put string-heavy stuff towards the end of the list, if it's harder to deal with.

I agree 100%. Too much tedium, not enough actual learning.
